### ISSUE TITLE
coin should be moved from user to state

### ISSUE THREAD

**Issue by joelnet** [joelnet/the-terminal-daemon#1]
Right now the `coin` attribute is stored in the `user` table. This should be moved to the newly created `state` table.

Files to change:
  - https://github.com/joelnet/the-terminal-daemon/blob/master/src/commands/wallet/strategies/balance.strategy.js
- https://github.com/joelnet/the-terminal-daemon/blob/master/src/commands/wallet/strategies/collect.strategy.js

Suggested Change: 

```javascript
# old
const user = tables.users.find({ username: req.session.username })[0]
const { coins = '0' } = user

# new
const { coins = 0 } = tables.state.get(username)
```

**Comment by guy-baron1** [comment]
I took this, pull requested

**Comment by parmentf** [comment]
It's the Pull Request #4.
I like linking issues (this one is #1) and PR (only naming the number, preceded with `#`).
It works for issues and PRs.

**Comment by joelnet** [comment]
@all-contributors please add @guy-baron1  for code
