### ISSUE TITLE
Refactor cat.strategy.js to use the strategy pattern

### ISSUE THREAD

**Issue by joelnet** [joelnet/the-terminal-daemon#11]
create a folder src/commands/cat and add files under that

Copy the way wallet.command.js works

Basically each if should become it's own strategy.js file. the default case is src/commands/wallet/strategies/invalid.strategy.js

**Comment by dl90** [comment]
ill attempt it (noob here) =D

**Comment by joelnet** [comment]
👍

**Comment by joelnet** [comment]
in the `the-terminal-daemon` project, run:

```bash
npm ci
```

that'll install all the dependencies.

**Comment by Ashirogi-Muto** [comment]
Hey, @joelnet is this issue still open?

**Comment by joelnet** [comment]
This one has a pending pull request that seems like it's still being worked on. I'd give it a little more time. You can pickup any other file in here: https://github.com/joelnet/the-terminal-daemon/tree/master/src/commands and do the same thing.

You can create an issue for it after picking a file or let me know on Discord and I'll create one.

**Comment by Ashirogi-Muto** [comment]
So all of the files in the command directory need to be refactored to follow the strategy pattern?

**Comment by joelnet** [comment]
Every one of them!

**Comment by Ashirogi-Muto** [comment]
I see! I'll start working on it and let you know if I have any doubts!

**Comment by dl90** [comment]
Sorry, I didn't have that much time. Feel free to pick this up if you'd like, I have finals and major milestones coming up in the next 3 weeks...

**Comment by Ashirogi-Muto** [comment]
That’s alright! I picked up another issue which is same as this one. Good luck mate! I just got done with my finals!!

**Comment by besesda** [comment]
ПРИВЕТ РЕБЯТ Я НОВИЧОК

**Comment by joelnet** [comment]
> ПРИВЕТ РЕБЯТ Я НОВИЧОК

Hello!

**Comment by joelnet** [comment]
@all-contributors please add @Ashirogi-Muto for code

**Comment by kp-dhvani** [comment]
Thanks a lot for helping me through this! This is my first PR and contribution to an open-source project!
