### ISSUE TITLE
refactor  cd.command.js to use strategy pattern

### ISSUE THREAD

**Issue by joelnet** [joelnet/the-terminal-daemon#18]
create a folder src/commands/cd and add files under that

Copy the way wallet.command.js works

Basically each if should become it's own strategy.js file. the default case is src/commands/wallet/strategies/invalid.strategy.js

Follow the directions in [CONTRIBUTING.md](https://github.com/joelnet/the-terminal-daemon/blob/master/CONTRIBUTING.md) for directions on how to test and debug your changes.

**Comment by Krayorn** [comment]
Hey, i'm gonna take that one :)

Got something already working but ran into a little issue with this part in `cd/strategies/invalid.strategy.js`
```
const { name } = require('../cd.command')

[…]
const exec = req => {
  const [command] = getArgs(req.body.line)
  return [actions.echo(`${name}: ${command}: Invalid command`)]
}

```

`name` is undefined, doesn't seems to work for the wallet command either
I'm gonna investigate and fix it, should submit a PR tomorrow

**Comment by joelnet** [comment]
Let me know if you need help with anything. Push some code up to a branch and I can have a look.

**Comment by Krayorn** [comment]
created the PR => [https://github.com/joelnet/the-terminal-daemon/pull/21](https://github.com/joelnet/the-terminal-daemon/pull/21)
