### ISSUE TITLE
create unit tests for cat.command.js

### ISSUE THREAD

**Issue by joelnet** [joelnet/the-terminal-daemon#19]
Create tests in `src/commands/__tests__/cat.command.test.js`.

use Jest.

Copy style from `src/filesystem/__tests__`

**Comment by p85** [comment]
can i take this one?

**Comment by joelnet** [comment]
👍

**Comment by p85** [comment]
I have a Question. Ive implemented the Test but when i run them via npm test, i get the message shown in the Screenshot. any Ideas?

My Changes in my Forked Repo: [here](https://github.com/p85/the-terminal-daemon/commit/883e644d6520a19ea4b57c821f9671a0c1954652)

Screenshot: 
![testerrormsg](https://user-images.githubusercontent.com/10893666/69218474-1af9a600-0b71-11ea-85e7-2313caa3153b.PNG)

**Comment by joelnet** [comment]
Those are normal. Just warnings. I'll suppress the warnings in another issue.

**Comment by p85** [comment]
ive submitted a pr #26

**Comment by joelnet** [comment]
@all-contributors please add @p85 for tests
