### ISSUE TITLE
Refactor adduser.command.js to use strategy pattern

### ISSUE THREAD

**Issue by joelnet** [joelnet/the-terminal-daemon#2]
Refactor `adduser.command.js` to use the strategy pattern.

create a folder `src/commands/adduser` and add files under that.

Copy the way `wallet.command.js` works.

Basically each `if` should become it's own `strategy.js` file. the default case is `src/commands/wallet/strategies/invalid.strategy.js`

**Comment by SamWolfs** [comment]
Is it cool if I have a go at this?

**Comment by joelnet** [comment]
Go for it. Let me know if you have any questions.

**Comment by aeciolevy** [comment]
@SamWolfs I already submit the PR for this issue, sorry if you had started.
@joelnet are you the reviewer?

**Comment by joelnet** [comment]
There's enough for everybody. All the commands needs to be refactored. Here's another issue: https://github.com/joelnet/the-terminal-daemon/issues/11

**Comment by joelnet** [comment]
@all-contributors please add @joelnet  for code
