### ISSUE TITLE
Modify welcome screen to include version number

### ISSUE THREAD

**Issue by joelnet** [joelnet/the-terminal-daemon#29]
The text seen during `npx the-terminal` need to be modified to add the version number.

The text `Welcome to Terminal` should read something like `Welcome to Terminal v1.2.3`

The version should be pulled from the package.json.

**Comment by sowmiyamuthuraman** [comment]
Working on this!

**Comment by joelnet** [comment]
Awesome! Join us on Discord if you wanna chat! https://discordapp.com/invite/Gg7ptD5

**Comment by joelnet** [comment]
@all-contributors please add @sowmiyamuthuraman  for code
