### ISSUE TITLE
Better docs?

### ISSUE THREAD

**Issue by BoDonkey** [joelnet/the-terminal-daemon#3]
When issuing 'npx the-terminal' I get the error:
"Fatal Error: Error: connect ECONNREFUSED 185.21.216.182:18000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)"
whether or not 'npm run-dev' has been issued

npm output: 
[nodemon] 1.19.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] starting `node src/index.js`
Listening on http://0.0.0.0:18000

Too much of a newbie to troubleshoot if it is me or a bug!

**Comment by parmentf** [comment]
True, the README is the same as [the-terminal-cli](https://github.com/joelnet/the-terminal-cli) one.
If you want to play locally, better use [DEV.md](../tree/master/DEV.md) which says how to launch the server/daemon.

**Comment by joelnet** [comment]
In my haste, I copied and pasted the 1 README. They should be different.

**Comment by evanplaice** [comment]
Sorry about the delay, here's a PR addressing this issue

**Comment by joelnet** [comment]
Cool beans. This will be a good start!

Thanks!

**Comment by joelnet** [comment]
@all-contributors please add @evanplaice for code
