### ISSUE TITLE
Wallet info should display on the prompt

### ISSUE THREAD

**Issue by joelnet** [joelnet/the-terminal-daemon#35]
When the wallet is ready to collect, the prompt should include a message "wallet: ready!"

When the wallet is not ready to collect show the balance `coin: 1.2`

Message should be in green, formatted similar to other prompt messages

Look at `canCollect` from https://github.com/joelnet/the-terminal-daemon/blob/master/src/commands/wallet/strategies/collect.strategy.js

Try to re-use the function instead of copying and pasting it into multiple locations.

Wallet info should only show if the `wallet` package has been installed.

**Comment by Krayorn** [comment]
Taking that one
