### ISSUE TITLE
Merge session-id and session middleware into one

### ISSUE THREAD

**Issue by joelnet** [joelnet/the-terminal-daemon#49]
Move the code from `session-id.middleware.js` into `session.middleware.js`

I don't think there's a reason to have two files dealing with sessions.

**Comment by cagomezr** [comment]
Good day Ill work on this and provide you a pull request shortly.

**Comment by joelnet** [comment]
Hey @cagomezr,

Your work looks great. I have merged it into master!

Thanks for your contribution!
