### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by dnafication** [joelnet/the-terminal-daemon#8]
Following the instructions on the DEV.md and README.md file. While issuing the `npx` command I get the following error. This is being run on windows 10 laptop with `node v10.15.2` and `npx v6.11.3`. Has anyone encountered this?

![image](https://user-images.githubusercontent.com/6381587/67612664-00414500-f7f0-11e9-8fdb-8f27ad4f0f88.png)

**Comment by emsknock** [comment]
I think the problem is that you're trying to run this on Windows. I just did a cold install on a Windows 10 and got the same issue but a cold install runs fine on MacOS. I'm not too familiar with the inner workings of `npx` but it seems like it doesn't like Windows's `PATH` and somehow gets confused.

**Comment by dnafication** [comment]
May be we can add a note in the documentation that it is not currently working with Windows. I'll have a crack at it later today.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by joelnet** [comment]
I'll check this out when I get access to a Windows machine. I have seen a few different issues with Windows, but I thought they were all resolved.

**Comment by joelnet** [comment]
Try running this https://www.npmjs.com/package/npkill and see if you get the same problems.

```bash
npx npkill
```

My install on Windows has a problem with `npx` for some reason. Troubleshooting now.

**Comment by joelnet** [comment]
This specific issue has been fixed. There may be other Windows related issues. Open a new ticket for new issues.

See updated [README](https://github.com/joelnet/the-terminal-daemon/blob/master/README.md) for Windows related fixes.
